import test from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, readFileSync } from 'node:fs';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import matter from 'gray-matter';

function setupArticleFixture() {
  const tmp = mkdtempSync(path.join(os.tmpdir(), 'transcrab-test-'));
  const contentRoot = path.join(tmp, 'content', 'articles');
  const slug = 't1';
  const dir = path.join(contentRoot, slug);
  fs.mkdirSync(dir, { recursive: true });

  const sourceMd = `---\ntitle: Source Title\ndate: 2026-02-07T00:00:00.000Z\nsourceUrl: https://example.com\nlang: source\n---\n\nBody`;
  writeFileSync(path.join(dir, 'source.md'), sourceMd, 'utf8');

  return { tmp, contentRoot, slug, dir };
}

test('apply-translation.mjs: extracts H1 title and writes frontmatter', () => {
  const { tmp, contentRoot, slug, dir } = setupArticleFixture();

  const translated = `# 译文标题\n\n这是正文第一段。\n\n- 列表项\n`;
  const inFile = path.join(tmp, 'translated.md');
  writeFileSync(inFile, translated, 'utf8');

  const script = path.resolve('scripts/apply-translation.mjs');
  const r = spawnSync(process.execPath, [script, slug, '--lang', 'zh', '--in', inFile], {
    env: { ...process.env, TRANSCRAB_CONTENT_ROOT: contentRoot },
    encoding: 'utf8',
  });
  assert.equal(r.status, 0, r.stderr || r.stdout);

  const out = JSON.parse(r.stdout.trim());
  assert.equal(out.ok, true);
  assert.equal(out.schema, 'transcrab.cli-result');
  assert.equal(out.schemaVersion, 1);
  assert.equal(out.status, 'complete');
  assert.equal(out.stage, 'final');

  const zh = readFileSync(path.join(dir, 'zh.md'), 'utf8');
  const parsed = matter(zh);
  assert.equal(parsed.data.title, '译文标题');
  assert.equal(parsed.data.sourceUrl, 'https://example.com');
  assert.equal(parsed.data.lang, 'zh');
  assert.ok(!/^#\s+/m.test(parsed.content.trim()));
  assert.match(parsed.content, /这是正文第一段/);
});

test('apply-translation.mjs: does not run Chinese punctuation fixes for other target languages', () => {
  const { tmp, contentRoot, slug, dir } = setupArticleFixture();
  const inFile = path.join(tmp, 'translated.en.md');
  writeFileSync(inFile, '# English title\n\nThe quoted source says 中文? Keep it exact.\n', 'utf8');

  const script = path.resolve('scripts/apply-translation.mjs');
  const r = spawnSync(process.execPath, [script, slug, '--lang', 'en', '--in', inFile], {
    env: { ...process.env, TRANSCRAB_CONTENT_ROOT: contentRoot },
    encoding: 'utf8',
  });
  assert.equal(r.status, 0, r.stderr || r.stdout);

  const out = JSON.parse(r.stdout.trim());
  assert.equal(out.autoFixed, false);
  assert.match(readFileSync(path.join(dir, 'en.md'), 'utf8'), /中文\?/);
});

test('apply-translation.mjs: rejects a target language that disagrees with prepared metadata', () => {
  const { tmp, contentRoot, slug, dir } = setupArticleFixture();
  writeFileSync(path.join(dir, 'meta.json'), JSON.stringify({ targetLang: 'en' }), 'utf8');
  const inFile = path.join(tmp, 'translated.fr.md');
  writeFileSync(inFile, '# Titre\n\nCorps.', 'utf8');

  const script = path.resolve('scripts/apply-translation.mjs');
  const r = spawnSync(process.execPath, [script, slug, '--lang', 'fr', '--in', inFile], {
    env: { ...process.env, TRANSCRAB_CONTENT_ROOT: contentRoot },
    encoding: 'utf8',
  });

  assert.notEqual(r.status, 0);
  assert.match(r.stderr + r.stdout, /task expects en, received fr/);
  assert.equal(fs.existsSync(path.join(dir, 'fr.md')), false);
});

test('apply-translation.mjs: draft stage writes draft+critique for refined flow', () => {
  const { tmp, contentRoot, slug, dir } = setupArticleFixture();

  // mimic refined profile generated by add-url
  writeFileSync(
    path.join(dir, 'translation.profile.json'),
    JSON.stringify({ executionMode: 'refined' }, null, 2),
    'utf8'
  );
  writeFileSync(
    path.join(dir, 'agent-task.json'),
    JSON.stringify({ schema: 'transcrab.agent-task', schemaVersion: 1, status: 'awaiting_translation' }),
    'utf8'
  );

  const translated = `# Draft 标题\n\n这是 draft 内容。\n\n\`\`\`js\nconsole.log(1)\n\`\`\``;
  const inFile = path.join(tmp, 'draft.md');
  writeFileSync(inFile, translated, 'utf8');

  const script = path.resolve('scripts/apply-translation.mjs');
  const r = spawnSync(process.execPath, [script, slug, '--lang', 'zh', '--in', inFile, '--stage', 'draft'], {
    env: { ...process.env, TRANSCRAB_CONTENT_ROOT: contentRoot },
    encoding: 'utf8',
  });
  assert.equal(r.status, 0, r.stderr || r.stdout);

  const out = JSON.parse(r.stdout.trim());
  assert.equal(out.schemaVersion, 1);
  assert.equal(out.status, 'draft_applied');
  assert.equal(out.stage, 'draft');

  const draftPath = path.join(dir, '03-draft.md');
  const critiquePath = path.join(dir, '04-critique.md');
  assert.ok(fs.existsSync(draftPath));
  assert.ok(fs.existsSync(critiquePath));
  assert.ok(!fs.existsSync(path.join(dir, 'zh.md')));

  const critique = readFileSync(critiquePath, 'utf8');
  assert.match(critique, /code-fence-balanced/);
  assert.doesNotMatch(critique, /TODO/);
  const task = JSON.parse(readFileSync(path.join(dir, 'agent-task.json'), 'utf8'));
  assert.equal(task.status, 'draft_applied');
  assert.deepEqual(task.completedStages, ['draft']);
});

test('apply-translation.mjs: draft stage in normal flow does not create critique file', () => {
  const { tmp, contentRoot, slug, dir } = setupArticleFixture();

  writeFileSync(
    path.join(dir, 'translation.profile.json'),
    JSON.stringify({ executionMode: 'normal' }, null, 2),
    'utf8'
  );

  const translated = `# 普通模式标题\n\n普通模式 draft 内容。`;
  const inFile = path.join(tmp, 'normal-draft.md');
  writeFileSync(inFile, translated, 'utf8');

  const script = path.resolve('scripts/apply-translation.mjs');
  const r = spawnSync(process.execPath, [script, slug, '--lang', 'zh', '--in', inFile, '--stage', 'draft'], {
    env: { ...process.env, TRANSCRAB_CONTENT_ROOT: contentRoot },
    encoding: 'utf8',
  });
  assert.equal(r.status, 0, r.stderr || r.stdout);

  assert.ok(fs.existsSync(path.join(dir, '03-draft.md')));
  assert.ok(!fs.existsSync(path.join(dir, '04-critique.md')));
});

test('apply-translation.mjs: rejects invalid stage', () => {
  const { tmp, contentRoot, slug } = setupArticleFixture();

  const translated = `# T\n\nBody`;
  const inFile = path.join(tmp, 'invalid-stage.md');
  writeFileSync(inFile, translated, 'utf8');

  const script = path.resolve('scripts/apply-translation.mjs');
  const r = spawnSync(process.execPath, [script, slug, '--lang', 'zh', '--in', inFile, '--stage', 'oops'], {
    env: { ...process.env, TRANSCRAB_CONTENT_ROOT: contentRoot },
    encoding: 'utf8',
  });
  assert.notEqual(r.status, 0);
  assert.match(r.stderr + r.stdout, /Invalid --stage/);
  const errorResult = JSON.parse(r.stderr.trim());
  assert.equal(errorResult.schema, 'transcrab.cli-result');
  assert.equal(errorResult.status, 'error');
  assert.equal(errorResult.ok, false);
});

test('apply-translation.mjs: rejects translations without the required H1 title', () => {
  const { tmp, contentRoot, slug } = setupArticleFixture();
  const inFile = path.join(tmp, 'missing-title.md');
  writeFileSync(inFile, 'Translated body without a title.', 'utf8');

  const script = path.resolve('scripts/apply-translation.mjs');
  const r = spawnSync(process.execPath, [script, slug, '--lang', 'zh', '--in', inFile], {
    env: { ...process.env, TRANSCRAB_CONTENT_ROOT: contentRoot },
    encoding: 'utf8',
  });

  assert.notEqual(r.status, 0);
  assert.match(r.stderr + r.stdout, /must start with an H1 title/);
});

test('apply-translation.mjs: refined final stage requires an applied draft', () => {
  const { tmp, contentRoot, slug, dir } = setupArticleFixture();
  writeFileSync(
    path.join(dir, 'translation.profile.json'),
    JSON.stringify({ executionMode: 'refined' }, null, 2),
    'utf8'
  );
  writeFileSync(
    path.join(dir, '03-draft.md'),
    '# Initial Translation Draft\n\n> Put the first complete translation here (H1 + blank line + body).\n',
    'utf8'
  );
  const inFile = path.join(tmp, 'premature-final.md');
  writeFileSync(inFile, '# Final title\n\nFinal body.', 'utf8');

  const script = path.resolve('scripts/apply-translation.mjs');
  const r = spawnSync(process.execPath, [script, slug, '--lang', 'zh', '--in', inFile, '--stage', 'final'], {
    env: { ...process.env, TRANSCRAB_CONTENT_ROOT: contentRoot },
    encoding: 'utf8',
  });

  assert.notEqual(r.status, 0);
  assert.match(r.stderr + r.stdout, /requires an applied draft/);
});

test('apply-translation.mjs: final stage applies punctuation auto-fix and writes lint report', () => {
  const { tmp, contentRoot, slug, dir } = setupArticleFixture();

  writeFileSync(
    path.join(dir, 'translation.profile.json'),
    JSON.stringify({ executionMode: 'refined' }, null, 2),
    'utf8'
  );
  writeFileSync(path.join(dir, '03-draft.md'), '# Draft\n\nold', 'utf8');

  const translated = `# 最终标题\n\n问题是? 这段中文?`;
  const inFile = path.join(tmp, 'final-lint.md');
  const reviewFile = path.join(tmp, 'review-lint.md');
  writeFileSync(inFile, translated, 'utf8');
  writeFileSync(reviewFile, '# Revision Notes\n\n- Checked terminology and punctuation.\n', 'utf8');

  const script = path.resolve('scripts/apply-translation.mjs');
  const r = spawnSync(process.execPath, [script, slug, '--lang', 'zh', '--in', inFile, '--stage', 'final', '--review-notes', reviewFile], {
    env: { ...process.env, TRANSCRAB_CONTENT_ROOT: contentRoot },
    encoding: 'utf8',
  });
  assert.equal(r.status, 0, r.stderr || r.stdout);

  const out = JSON.parse(r.stdout.trim());
  assert.equal(out.autoFixed, true);
  assert.ok(fs.existsSync(path.join(dir, 'lint.report.json')));

  const zh = readFileSync(path.join(dir, 'zh.md'), 'utf8');
  assert.match(zh, /问题在于：/);
  assert.match(zh, /中文？/);
});

test('apply-translation.mjs: final stage writes revision notes for refined flow', () => {
  const { tmp, contentRoot, slug, dir } = setupArticleFixture();

  writeFileSync(
    path.join(dir, 'translation.profile.json'),
    JSON.stringify({ executionMode: 'refined' }, null, 2),
    'utf8'
  );
  writeFileSync(path.join(dir, '03-draft.md'), '# Draft\n\nold', 'utf8');
  writeFileSync(
    path.join(dir, 'agent-task.json'),
    JSON.stringify({ schema: 'transcrab.agent-task', schemaVersion: 1, status: 'draft_applied', completedStages: ['draft'] }),
    'utf8'
  );

  const translated = `# 最终标题\n\n最终正文。`;
  const inFile = path.join(tmp, 'final.md');
  const reviewFile = path.join(tmp, 'review.md');
  writeFileSync(inFile, translated, 'utf8');
  writeFileSync(reviewFile, '# Revision Notes\n\n- Verified accuracy, terms, structure, and readability.\n', 'utf8');

  const script = path.resolve('scripts/apply-translation.mjs');
  const r = spawnSync(process.execPath, [script, slug, '--lang', 'zh', '--in', inFile, '--stage', 'final', '--review-notes', reviewFile], {
    env: { ...process.env, TRANSCRAB_CONTENT_ROOT: contentRoot },
    encoding: 'utf8',
  });
  assert.equal(r.status, 0, r.stderr || r.stdout);

  assert.ok(fs.existsSync(path.join(dir, 'zh.md')));
  assert.ok(fs.existsSync(path.join(dir, '05-revision.md')));
  assert.doesNotMatch(readFileSync(path.join(dir, '05-revision.md'), 'utf8'), /TODO/);
  const task = JSON.parse(readFileSync(path.join(dir, 'agent-task.json'), 'utf8'));
  assert.equal(task.status, 'complete');
  assert.deepEqual(task.completedStages, ['draft', 'final']);
});

test('apply-translation.mjs: refined final stage requires completed review notes', () => {
  const { tmp, contentRoot, slug, dir } = setupArticleFixture();
  writeFileSync(
    path.join(dir, 'translation.profile.json'),
    JSON.stringify({ executionMode: 'refined' }, null, 2),
    'utf8'
  );
  writeFileSync(path.join(dir, '03-draft.md'), '# Draft\n\nDraft body.', 'utf8');
  const inFile = path.join(tmp, 'final-without-review.md');
  writeFileSync(inFile, '# Final title\n\nFinal body.', 'utf8');

  const script = path.resolve('scripts/apply-translation.mjs');
  const r = spawnSync(process.execPath, [script, slug, '--lang', 'zh', '--in', inFile, '--stage', 'final'], {
    env: { ...process.env, TRANSCRAB_CONTENT_ROOT: contentRoot },
    encoding: 'utf8',
  });

  assert.notEqual(r.status, 0);
  assert.match(r.stderr + r.stdout, /requires --review-notes/);
});

test('apply-translation.mjs: a complete durable task cannot regress to draft', () => {
  const { tmp, contentRoot, slug, dir } = setupArticleFixture();
  const taskPath = path.join(dir, 'agent-task.json');
  const completedTask = {
    schema: 'transcrab.agent-task',
    schemaVersion: 1,
    status: 'complete',
    completedStages: ['draft', 'final'],
    article: { slug, targetLanguage: 'zh' },
  };
  writeFileSync(taskPath, JSON.stringify(completedTask, null, 2), 'utf8');
  writeFileSync(path.join(dir, 'meta.json'), JSON.stringify({ targetLang: 'zh' }), 'utf8');
  const inFile = path.join(tmp, 'late-draft.md');
  writeFileSync(inFile, '# Late draft\n\nShould not apply.', 'utf8');

  const script = path.resolve('scripts/apply-translation.mjs');
  const r = spawnSync(process.execPath, [script, slug, '--lang', 'zh', '--in', inFile, '--stage', 'draft'], {
    env: { ...process.env, TRANSCRAB_CONTENT_ROOT: contentRoot },
    encoding: 'utf8',
  });

  assert.notEqual(r.status, 0);
  assert.match(r.stderr + r.stdout, /Cannot apply a draft.*complete/);
  assert.deepEqual(JSON.parse(readFileSync(taskPath, 'utf8')), completedTask);
  assert.equal(fs.existsSync(path.join(dir, '03-draft.md')), false);
});

test('apply-translation.mjs: restores inline SVG placeholders in output', () => {
  const { tmp, contentRoot, slug, dir } = setupArticleFixture();

  writeFileSync(
    path.join(dir, 'inline-svg.placeholders.json'),
    JSON.stringify([
      {
        id: '@@FIGURE_SVG_001@@',
        html: '<figure><p class="figure-title">Demo</p><svg><text>中文?</text></svg></figure>',
      },
    ], null, 2),
    'utf8'
  );

  const translated = `# 标题\n\n段落前。\n\n@@FIGURE_SVG_001@@\n\n段落后。`;
  const inFile = path.join(tmp, 'with-placeholder.md');
  writeFileSync(inFile, translated, 'utf8');

  const script = path.resolve('scripts/apply-translation.mjs');
  const r = spawnSync(process.execPath, [script, slug, '--lang', 'zh', '--in', inFile, '--stage', 'final'], {
    env: { ...process.env, TRANSCRAB_CONTENT_ROOT: contentRoot },
    encoding: 'utf8',
  });
  assert.equal(r.status, 0, r.stderr || r.stdout);

  const zh = readFileSync(path.join(dir, 'zh.md'), 'utf8');
  assert.doesNotMatch(zh, /@@FIGURE_SVG_001@@/);
  assert.match(zh, /<figure>/);
  assert.match(zh, /<svg>/);
  assert.match(zh, /<text>中文\?<\/text>/);
});

test('apply-translation.mjs: fails when inline SVG placeholders are missing', () => {
  const { tmp, contentRoot, slug, dir } = setupArticleFixture();

  writeFileSync(
    path.join(dir, 'inline-svg.placeholders.json'),
    JSON.stringify([{ id: '@@FIGURE_SVG_001@@', html: '<figure><svg></svg></figure>' }], null, 2),
    'utf8'
  );

  const translated = `# 标题\n\n没有占位符。`;
  const inFile = path.join(tmp, 'missing-placeholder.md');
  writeFileSync(inFile, translated, 'utf8');

  const script = path.resolve('scripts/apply-translation.mjs');
  const r = spawnSync(process.execPath, [script, slug, '--lang', 'zh', '--in', inFile], {
    env: { ...process.env, TRANSCRAB_CONTENT_ROOT: contentRoot },
    encoding: 'utf8',
  });

  assert.notEqual(r.status, 0);
  assert.match(r.stderr + r.stdout, /Missing inline SVG placeholders/);
});

test('apply-translation.mjs: does not silently ignore corrupt pipeline state', () => {
  const { tmp, contentRoot, slug, dir } = setupArticleFixture();
  writeFileSync(path.join(dir, 'translation.profile.json'), '{broken', 'utf8');
  const inFile = path.join(tmp, 'valid-translation.md');
  writeFileSync(inFile, '# Valid title\n\nValid body.', 'utf8');

  const script = path.resolve('scripts/apply-translation.mjs');
  const r = spawnSync(process.execPath, [script, slug, '--lang', 'zh', '--in', inFile], {
    env: { ...process.env, TRANSCRAB_CONTENT_ROOT: contentRoot },
    encoding: 'utf8',
  });

  assert.notEqual(r.status, 0);
  assert.match(r.stderr + r.stdout, /Invalid translation profile JSON/);
});

test('apply-translation.mjs: rejects a corrupt durable agent task before publishing', () => {
  const { tmp, contentRoot, slug, dir } = setupArticleFixture();
  writeFileSync(path.join(dir, 'agent-task.json'), '{broken', 'utf8');
  const inFile = path.join(tmp, 'valid-final.md');
  writeFileSync(inFile, '# Valid title\n\nValid body.', 'utf8');

  const script = path.resolve('scripts/apply-translation.mjs');
  const r = spawnSync(process.execPath, [script, slug, '--lang', 'zh', '--in', inFile], {
    env: { ...process.env, TRANSCRAB_CONTENT_ROOT: contentRoot },
    encoding: 'utf8',
  });

  assert.notEqual(r.status, 0);
  assert.match(r.stderr + r.stdout, /Invalid agent task JSON/);
  assert.equal(fs.existsSync(path.join(dir, 'zh.md')), false);
});

test('apply-translation.mjs: rejects malformed inline SVG placeholder state', () => {
  const { tmp, contentRoot, slug, dir } = setupArticleFixture();
  writeFileSync(path.join(dir, 'inline-svg.placeholders.json'), JSON.stringify([{}]), 'utf8');
  const inFile = path.join(tmp, 'valid-placeholder-final.md');
  writeFileSync(inFile, '# Valid title\n\nValid body.', 'utf8');

  const script = path.resolve('scripts/apply-translation.mjs');
  const r = spawnSync(process.execPath, [script, slug, '--lang', 'zh', '--in', inFile], {
    env: { ...process.env, TRANSCRAB_CONTENT_ROOT: contentRoot },
    encoding: 'utf8',
  });

  assert.notEqual(r.status, 0);
  assert.match(r.stderr + r.stdout, /invalid entries/);
  assert.equal(fs.existsSync(path.join(dir, 'zh.md')), false);
});
